// Turns google-services.json into the string resources Firebase reads at
// startup, the same ones the Google Services gradle plugin would generate.
//
// That plugin cannot do the job here. A gradle file shipped by a Cordova plugin
// is evaluated in its own classloader, where the Android Gradle Plugin is
// invisible, so the Google Services plugin fails to load with
// NoClassDefFoundError on com/android/build/api/variant/Variant. And
// cordova-android's own handling, driven by GradlePluginGoogleServicesEnabled,
// does not reach MABS — the JSON then ships inside the APK unread and
// registration fails with "Failed to retrieve token".
//
// Reading the file here needs neither.

var path = require("path");
var fs = require("fs");
var utils = require("./utils");

var RESOURCE_FILE = "pushwoosh-google-services.xml";

function appPackageName() {
    var xml = fs.readFileSync("config.xml", "utf8");
    var match = xml.match(/id="([^"]+)"/);
    return match ? match[1] : null;
}

// google-services.json describes every app in the Firebase project; only the
// entry matching this package carries usable credentials.
function findClient(config, packageName) {
    var clients = config.client || [];
    for (var i = 0; i < clients.length; i++) {
        var info = clients[i].client_info || {};
        var android = info.android_client_info || {};
        if (android.package_name === packageName) {
            return clients[i];
        }
    }
    return null;
}

function escapeXml(value) {
    return String(value)
        .replace(/&/g, "&amp;")
        .replace(/</g, "&lt;")
        .replace(/>/g, "&gt;")
        .replace(/"/g, "&quot;");
}

function buildResources(config, client) {
    var project = config.project_info || {};
    var apiKey = (client.api_key || [])[0] || {};

    var values = {
        google_app_id: (client.client_info || {}).mobilesdk_app_id,
        gcm_defaultSenderId: project.project_number,
        google_api_key: apiKey.current_key,
        google_crash_reporting_api_key: apiKey.current_key,
        project_id: project.project_id,
        firebase_database_url: project.firebase_url,
        google_storage_bucket: project.storage_bucket,
    };

    var lines = [
        '<?xml version="1.0" encoding="utf-8"?>',
        "<!-- Generated by the Pushwoosh plugin from google-services.json. -->",
        "<resources>",
    ];
    Object.keys(values).forEach(function (name) {
        if (values[name]) {
            lines.push(
                '    <string name="' + name + '" translatable="false">' + escapeXml(values[name]) + "</string>"
            );
        }
    });
    lines.push("</resources>", "");
    return lines.join("\n");
}

module.exports = function (context) {
    return new Promise(function (resolve, reject) {
        if (context.opts.plugin.platform !== "android") {
            return resolve();
        }

        var platformPath = utils.getPlatformPath(context);
        var jsonPath = path.join(platformPath, "app", "google-services.json");
        if (!fs.existsSync(jsonPath)) {
            return reject(
                "Failed to install Pushwoosh plugin. Reason: google-services.json was not placed in the Android project."
            );
        }

        var packageName = appPackageName();
        var config;
        try {
            config = JSON.parse(fs.readFileSync(jsonPath, "utf8"));
        } catch (error) {
            return reject(
                "Failed to install Pushwoosh plugin. Reason: google-services.json is not valid JSON: " + error.message
            );
        }

        var client = findClient(config, packageName);
        if (!client) {
            return reject(
                "Failed to install Pushwoosh plugin. Reason: google-services.json has no configuration for " +
                    packageName +
                    ". Add this application to the Firebase project and download the file again."
            );
        }

        var resDir = path.join(platformPath, "app", "src", "main", "res", "values");
        fs.mkdirSync(resDir, { recursive: true });
        fs.writeFileSync(path.join(resDir, RESOURCE_FILE), buildResources(config, client));

        console.log("[PUSHWOOSH HELPER] Firebase resources generated for " + packageName);
        return resolve();
    });
};
